### PR TITLE
add the run function

### PR DESCRIPTION
**Pull request by red-elka**
Hi!
i followed the installation guide of your program on a Linux machine (python v3.10.2), it didn't work, however i added a run function and i run it with `python3 app.py` and it seems to work

### CODE REVIEW

**Comment by abhinayy0** [comment]
Hi, thanks for pointing that out it seems, you might have missed to activate the python3 virtual environment before running the run.sh file. 
Did you try to activate the virtual environment and set the run.sh file as executable by chmod +x run.sh   

After that you should try  to run it. The change that you have made works too but in bigger flask apps, this is the standard way to follow.

**Comment by red-elka** [comment]
Yes, i did run it in a venv but it didn't work
I also added the +x permission to the file but it didn't want to work.

**Comment by abhinayy0** [comment]
Can you share the screenshot while trying to run. And specific error that it's giving.

**Comment by red-elka** [comment]
yeah man it works fine. 😅
but you should mention it (the virtualenv)

**Pull request merged**
